services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    entrypoint: [
        "/bin/sh",
        "-c",
        "export MIGRATE=0 &&
        python manage.py migrate &&
        export MIGRATE=1 &&
        python manage.py collectstatic --noinput &&
        gunicorn server.wsgi:application --bind 0.0.0.0:8000",
      ]
    expose:
      - 8000
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql@16.3/data/

    env_file:
      - .env.prod.db

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.certi
    restart: always
    depends_on:
      - web
      - db
    ports:
      - 80:80
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt

  certbot:
    image: certbot/certbot

    volumes:
      - certbot-web:/vol/www/certbot
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/vol/www/certbot --email python.mailverify@gmail.com -d=rish-kun.live -agree-tos

volumes:
  certbot-web:
  certbot-certs:
  postgres_data:
  static_volume:
