services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - static:/static
    command: python3 manage.py migrate && gunicorn server.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - server/.env
    depends_on:
      - db
  db:
    container_name: db-prod
    image: postgres:16.3-alpine
    env_file:
      - .env.prod.db

    volumes:
      - postgres_data:/var/lib/postgresql@16.3/data/

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - static:/static
    depends_on:
      - web
      - db
volumes:
  postgres_data:
  static:
