version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn --chdir /app/web/server server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/server/staticfiles
      - media_volume:/home/app/web/server/mediafiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/server/staticfiles
      - media_volume:/home/app/web/server/mediafiles
    ports:
      - "8080:8080"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
